apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  #storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
#  capacity:
#    storage: 10Gi
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: /tmp/jenkins-data


